### ISSUE TITLE
Error instalación 

### ISSUE THREAD

**Issue by hiddenotebook** [janc18/RTL8188FTV-Raspbian#2]
Hola me gustaria usar el driver pero me da problemas una manita please.

Intento instalar en raspberry pi2 y a partir de este directorio /lib/modules/5.15.76-v7+/build no hay nada despues de build esta en blanco 

```
dpkg: error: no se puede acceder al archivo '**.deb': No existe el fichero o el directorio
ln: fallo al crear el enlace simbólico '/lib/modules/5.15.76-v7+/build/arch/armv7l': No existe el fichero o el directorio
Error! Could not find module source directory.
Directory: /usr/src/.-rtl8188fu-arm does not exist.
Error! echo
Your kernel headers for kernel 5.15.76-v7+ cannot be found at
/lib/modules/5.15.76-v7+/build or /lib/modules/5.15.76-v7+/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
Error! echo
Your kernel headers for kernel 5.15.76-v7+ cannot be found at
/lib/modules/5.15.76-v7+/build or /lib/modules/5.15.76-v7+/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
cp: no se puede efectuar `stat' sobre './rtl8188fu-arm/firmware/rtl8188fufw.bin': No existe el fichero o el directorio
options rtl8188fu rtw_power_mgnt=0 rtw_enusbss=0
alias usb:v0BDApF179d*dc*dsc*dp*icFFiscFFipFFin* rtl8188fu
```

**Comment by janc18** [comment]
Hola que tal, si instalaste los siguientes paquetes:"build-essential","dkms","raspberrypi-kernel-headers"

Ademas, si moviste el archivo Instalador.sh a la carpeta de Descarga_de_paquetes que se creo?

**Comment by hiddenotebook** [comment]
Los paquetes si están instalados, ahora el instalador.sh no lo puse allá donde comentas, voy a seguir tu consejo y te cuento. Muchas gracias por la atención.

**Comment by janc18** [comment]
ok, si aún sigues teniendo algun problema te puedes comunicar a mi discord:El ing.#8549 , actualize el README, por que me faltaba añadir ese paso.
