### ISSUE TITLE
The program can not run correctly when I run the main.py. I am very grateful if you can give me  advice.

### ISSUE THREAD

**Issue by braoadlythinking22** [janc18/RTL8188FTV-Raspbian#5]
![图片](https://github.com/user-attachments/assets/ba8f85d0-6285-45e8-a9e8-e91e32207d69)
![屏幕截图 2024-12-08 111407](https://github.com/user-attachments/assets/c7b71a5a-80d3-4940-a463-82a1639a3e86)

![屏幕截图 2024-12-08 112332](https://github.com/user-attachments/assets/3686bc04-f246-4088-8d7b-fe6f8cd72284)
![屏幕截图 2024-12-08 112546](https://github.com/user-attachments/assets/242c7541-5bd8-4e89-94e8-7491c0872023)

**Comment by janc18** [comment]
Ok, thanks for sharing the issue let me check that

😀

**Comment by janc18** [comment]
Hello @braoadlythinking22 , I remember that it's not posible to install the driver with the last kernel version of Linux, to get around this issue i found a deb package or binary with the driver ready to install, but I don't remember the link, and I don't have a raspberry with me, so I can't help out with that right now.
